language: java
jdk:
#  - openjdk6
#  - oraclejdk7
#  - oraclejdk8
  - openjdk7

before_install:
  - mvn install -DskipTests=true -e

script:
  - mvn test -X

after_success:
  - mvn clean cobertura:cobertura coveralls:report -P ci

branches:
  except:
    - gh-pages

